name: konami_code
version: 1.2.0
description: A Dart implementation for Konami code.
author: Nicolas Francois @nicofrancois
homepage: https://github.com/nfrancois/KonamiDart
dependencies:
  browser: any
dev_dependencies:
  unittest: any
