name: konami_code
version: 1.2.1
author: Nicolas Francois  <nicolas.franc@gmail.com>
description: A Dart implementation for Konami code.
homepage: https://github.com/nfrancois/KonamiDart
environnement:
  sdk: ">=0.8.10+6 <2.0.0" 
dependencies:
  browser: '>=0.9.0 < 0.10.0 '
dev_dependencies:
  unittest: '>=0.9.0 < 0.10.0'
