name: konami_code
version: 1.1.0-dev
description: A Dart implementation for Konami code.
author: Nicolas Francois @nicofrancois
homepage: https://github.com/nfrancois/KonamiDart
dependencies:
  unittest: { sdk: unittest }
