name: konami_code
version: 1.2.0
author: Nicolas Francois  <nicolas.franc@gmail.com>
description: A Dart implementation for Konami code.
homepage: https://github.com/nfrancois/KonamiDart
dependencies:
  browser: '>=0.5.5'
dev_dependencies:
  unittest: any
